version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - frontend_html:/usr/share/nginx/html:ro
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
      cache_from:
        - streetview-backend:latest
    image: streetview-backend:latest
    env_file:
      - ./backend/.env
    expose:
      - "8080"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
      cache_from:
        - streetview-frontend:latest
    image: streetview-frontend:latest
    env_file:
      - ./frontend/.env
    volumes:
      - frontend_html:/app/html
    restart: always

  redis:
    image: redis:7.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

volumes:
  redis_data:
  frontend_html: 