version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      cache_from:
        - streetview-nginx:latest
    image: streetview-nginx:latest
    volumes:
      - frontend_html:/usr/share/nginx/html:ro
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
      cache_from:
        - streetview-backend:latest
    image: streetview-backend:latest
    env_file:
      - ./backend/.env
    expose:
      - "8080"
    depends_on:
      redis:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
      cache_from:
        - streetview-frontend:latest
    image: streetview-frontend:latest
    env_file:
      - ./frontend/.env
    volumes:
      - frontend_html:/app/html
    restart: always

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
      cache_from:
        - streetview-redis:latest
    image: streetview-redis:latest
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    restart: always

volumes:
  redis_data:
  frontend_html: 