services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - FRONTEND_BUILD_CONTEXT=./frontend
    image: streetview-nginx:latest
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    image: streetview-backend:latest
    env_file:
      - ./backend/.env
    environment:
      - REDIS_ADDRESS=redis:6379
    expose:
      - "8080"
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  redis:
    image: redis:7.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data
    expose:
      - "6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

volumes:
  redis_data: 